apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adaptive.controlPlane.fullname" . }}
  namespace: {{ .Release.Namespace}}
  {{- with .Values.controlPlane.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "adaptive.labels" . | nindent 4 }}
    {{- include "adaptive.controlPlane.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controlPlane.replicaCount | default 1 | int }}
  selector:
    matchLabels:
      {{- include "adaptive.controlPlane.selectorLabels" . | nindent 6}}
  template:
    metadata:
      {{- with .Values.controlPlane.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "adaptive.labels" . | nindent 8 }}
        {{- include "adaptive.controlPlane.selectorLabels" . | nindent 8 }}
        {{- with .Values.controlPlane.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector:
        {{- with .Values.controlPlane.nodeSelector}}
        {{ toYaml . }}
        {{- end}}
      {{- if .Values.controlPlane.tolerations}}
      tolerations:
        {{- toYaml .Values.controlPlane.tolerations | nindent 8 }}
      {{- end}}
      {{- if .Values.controlPlane.affinity}}
      affinity:
        {{- toYaml .Values.controlPlane.affinity | nindent 8 }}
      {{- end}}
      {{- if .Values.controlPlane.topologySpreadConstraints}}
      topologySpreadConstraints:
        {{- toYaml .Values.controlPlane.topologySpreadConstraints | nindent 8 }}
      {{- end}}
      {{- $ports := include "adaptive.controlPlane.ports" . | fromJson }}
      containers:
        - name: control-plane
          image: "{{ include "adaptive.controlPlane.imageUri" . }}"
          imagePullPolicy: {{ .Values.controlPlane.image.pullPolicy }}
          ports:
            - containerPort: {{ $ports.http.containerPort }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- include "adaptive.otelCollector.envVars" . | nindent 12 }}
            {{- include "adaptive.harmony.secretEnvVars" . | nindent 12 }}
            {{- include "adaptive.redis.secretEnvVars" . | nindent 12 }}
            - name: ADAPTIVE_DB__USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "adaptive.controlPlane.secret.fullname" . }}
                  key: dbUsername
            - name: ADAPTIVE_DB__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "adaptive.controlPlane.secret.fullname" . }}
                  key: dbPassword
            - name: ADAPTIVE_DB__HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "adaptive.controlPlane.secret.fullname" . }}
                  key: dbHost
            - name: ADAPTIVE_DB__DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "adaptive.controlPlane.secret.fullname" . }}
                  key: dbName
            - name: ADAPTIVE_APP__SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "adaptive.controlPlane.secret.fullname" . }}
                  key: cookiesSecret
            - name: ADAPTIVE_AUTH__OIDC__PROVIDERS
              valueFrom:
                secretKeyRef:
                  name: {{ include "adaptive.controlPlane.secret.fullname" . }}
                  key: oidcProviders
            - name: ADAPTIVE_HARMONY__SHARED_DIRECTORY__TYPE
              value: {{ .Values.controlPlane.sharedDirType | quote }}
            - name: ADAPTIVE_DB__RUN_MIGRATIONS
              value: {{ .Values.controlPlane.runDbMigrations | default true | quote }}
            - name: ADAPTIVE_SERVER__BIND
              value: "0.0.0.0:{{ $ports.http.containerPort }}"
            - name: ADAPTIVE_SERVER__ROOT_URL
              value: {{ .Values.controlPlane.rootUrl }}
            - name: IMAGE_TAG
              value: {{ .Values.controlPlane.image.tag | quote }}
            - name: ADAPTIVE_AUTH__SESSION__SECURE
              value: {{ .Values.auth.session.secure | default "true" | quote }}
            - name: ADAPTIVE_AUTH__SESSION__EXPIRATION_SECONDS
              value: {{ .Values.auth.session.expiration_seconds | default "518400" | quote }}
            - name: ADAPTIVE_AUTH__DEFAULT_TEAM
              value: {{ .Values.auth.default_team | default "default" | quote }}
            - name: ADAPTIVE_AUTH__DEFAULT_ROLE
              value: {{ .Values.auth.default_role | default "admin" | quote }}
            - name: ADAPTIVE_AUTH__ADMINS
              value: {{ .Values.auth.admins | toJson |  default "[]" | squote }}
            {{- $harmonyPorts := include "adaptive.harmony.ports" . | fromJson }}
            {{- if .Values.mlflow.enabled }}
            - name: ADAPTIVE_MLFLOW__ENABLED
              value: "true"
            - name: ADAPTIVE_MLFLOW__URL
              value: "{{ include "adaptive.mlflow.trackingUrl" . }}"
            - name: MLFLOW_TRACKING_URI
              value: "{{ include "adaptive.mlflow.trackingUrl" . }}"
            {{- end }}
            {{- if .Values.controlPlane.extraEnvVars }}
            {{- range $key, $value := .Values.controlPlane.extraEnvVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          {{- if .Values.controlPlane.resources }}
          resources:
            {{- toYaml .Values.controlPlane.resources | nindent 12 }}
          {{- end }}
