apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adaptive.sandkasten.fullname" . }}
  namespace: {{ .Release.Namespace}}
  labels:
    {{- include "adaptive.labels" . | nindent 4 }}
    {{- include "adaptive.sandkasten.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.sandkasten.replicaCount | default 1 | int }}
  selector:
    matchLabels:
      {{- include "adaptive.sandkasten.selectorLabels" . | nindent 6}}
  template:
    metadata:
      {{- with .Values.sandkasten.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "adaptive.labels" . | nindent 8 }}
        {{- include "adaptive.sandkasten.selectorLabels" . | nindent 8 }}
        {{- with .Values.sandkasten.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      volumes:
        - name: working-dir
          emptyDir: {}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      nodeSelector:
        {{- with .Values.sandkasten.nodeSelector}}
        {{ toYaml . }}
        {{- end}}
      {{- if .Values.sandkasten.tolerations}}
      tolerations:
        {{- toYaml .Values.sandkasten.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.sandkasten.affinity}}
      affinity:
        {{- toYaml .Values.sandkasten.affinity | nindent 8 }}
      {{- end}}
      {{- if .Values.sandkasten.topologySpreadConstraints}}
      topologySpreadConstraints:
        {{- toYaml .Values.sandkasten.topologySpreadConstraints | nindent 8 }}
      {{- end}}
      containers:
        - name: sandkasten
          image: "{{ include "adaptive.sandkasten.imageUri" . }}"
          imagePullPolicy: {{ .Values.sandkasten.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
          ports:
            - containerPort: {{ .Values.sandkasten.servicePort }}
          {{- if .Values.sandkasten.resources }}
          resources:
            {{- toYaml .Values.sandkasten.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: working-dir
              mountPath: /working_dir
          env:
            {{- include "adaptive.otelCollector.envVars" . | nindent 12 }}
            {{- include "adaptive.redis.secretEnvVars" . | nindent 12 }}
            - name: HARMONY_WS_ENDPOINT
              value: "{{ include "adaptive.harmony.wsEndpoint" . }}"
            - name: CONTROL_PLANE_URL
              value: "http://{{ include "adaptive.controlPlane.service.fullname" . }}:{{ .Values.controlPlane.servicePort | default 80 }}"
            {{- if .Values.sandkasten.extraEnvVars }}
            {{- range $key, $value := .Values.sandkasten.extraEnvVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
